name: univer_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.6
  url_launcher:
  dio:
  http:
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  onesignal_flutter: ^5.0.0
  flutter_inappwebview: ^5.8.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  # cached_network_image: ^3.4.1
  # dio: ^5.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: SF
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.ttf
    - family: SFM
      fonts:
        - asset: assets/fonts/SF-UI-Display-Medium.ttf
    - family: SFB
      fonts:
        - asset: assets/fonts/SF-UI-Display-Bold.ttf